### ISSUE TITLE
Allow unkown countries

### ISSUE THREAD

**Issue by ezruneko** [PascalMinder/GeoBlock#9]
Hi,

Some ips (for example ips from google assistant) all request are rejected because the plugins reject any ip with an unkown countries like:
https://app.geojs.io/s/66.249.93.100

Is it possible to allow unkown countries?

66.249.93.97 - - [29/Dec/2021:07:59:09 +0000] "POST /api/google_assistant HTTP/2.0" 403 0 "-" "-" 3 "home@file" "-" 76ms
66.249.81.244 - - [29/Dec/2021:07:59:10 +0000] "POST /api/google_assistant HTTP/2.0" 403 0 "-" "-" 4 "home@file" "-" 34ms

time="2021-12-29T08:59:09+01:00" level=error msg="2021/12/29 08:59:09 API response has more than 2 characters" plugin=plugin-GeoBlock module=github.com/PascalMinder/GeoBlock

time="2021-12-29T08:59:10+01:00" level=error msg="2021/12/29 08:59:10 API response has more than 2 characters" plugin=plugin-GeoBlock module=github.com/PascalMinder/GeoBlock

**Comment by PascalMinder** [comment]
Hi @ezruneko 
Thanks for your issue. I'll look into it.

**Comment by Thom-x** [comment]
Got the same issue from https://get.geojs.io/v1/ip/country/66.249.93.166, also for google assistant.

**Comment by PascalMinder** [comment]
One option could be to add a configuration option for a list of allowed IPs, or an additional configuration option to allow IPs with unknown origins.

**Comment by ezruneko** [comment]
Google has not published a list of ips ranges for Google Assistant.

I think the best option is to add a new country like Cloudflare which adds a fictitious country called XX.

![imagen](https://user-images.githubusercontent.com/1853429/147732038-bb34fe62-844c-40d9-abb9-e239781b5cad.png)

**Comment by ezruneko** [comment]
A possible option to implement it could be:

// https://github.com/PascalMinder/GeoBlock/blob/113267541ac037199cb4f9237227f3a9700d5537/geoblock.go#L201

```
	sb := string(body)
	countryCode := strings.TrimSuffix(sb, "\n")

        if countryCode  == "nil"  {
             countryCode  := "XX"
        }

	// this could possible cause a DoS attack
	if len([]rune(countryCode)) != 2 {
		return "", fmt.Errorf("API response has more than 2 characters")
	}
```

**Comment by PascalMinder** [comment]
Currently, you can use your own look-up API (changing the API string in the configuration). The geojs API returns nil if the IP has no country assigned. But they did not document it on their API documentation page (https://www.geojs.io/docs/v1/endpoints/country/).
I might also add a second option to define the "nil"-country code.

**Comment by ezruneko** [comment]
yes, it's true. in my opinion the best option is add theese second option to define the "nil" country code.

**Comment by PascalMinder** [comment]
I have added the options to release 0.1.7.

**Comment by Thom-x** [comment]
Still got the same error:

```
time="2021-12-30T10:47:00Z" level=error msg="2021/12/30 10:47:00 API response has more than 2 characters" module=github.com/PascalMinder/GeoBlock plugin=plugin-GeoBlock
```

For IP `66.249.93.168` with this config:

```toml
[experimental.plugins.GeoBlock]
  moduleName = "github.com/PascalMinder/GeoBlock"
  version = "v0.1.7"

[http.middlewares]
  [http.middlewares.geoblock]
    [http.middlewares.geoblock.plugin]
      [http.middlewares.geoblock.plugin.GeoBlock]
        allowlocalrequests = true
        loglocalrequests = false
        allowunknowncountries = true
        unknownCountryCode = "nil"
        cachesize = 1000
        api = "https://get.geojs.io/v1/ip/country/{ip}"
        countries = [
            "FR",  # France
        ]
```

BTW if `cachesize `is not set I got an error.

```
reverse-proxy_1  | time="2021-12-30T10:40:21Z" level=error msg="plugins-storage/sources/gop-3537769618/src/github.com/PascalMinder/GeoBlock/geoblock.go:67:9: panic" plugin=plugin-GeoBlock module=github.com/PascalMinder/GeoBlock
reverse-proxy_1  | time="2021-12-30T10:40:21Z" level=error msg="Error in Go routine: cache size must be bigger than 1"
reverse-proxy_1  | time="2021-12-30T10:40:21Z" level=error msg="Stack: goroutine 89 [running]:\nruntime/debug.Stack()\n\t/usr/local/golang/1.10.8/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x2d464c0, 0xc000fef110})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:56 +0x36\npanic({0x2d464c0, 0xc000fef110})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x145\npanic({0x2d464c0, 0xc000fef110})\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215\nlog.(*Logger).Panic(0x1, {0xc000fef090, 0x3, 0x0})\n\t/usr/local/golang/1.10.8/go/src/log/log.go:224 +0x69\nreflect.Value.call({0x2d38480, 0xc0009b8070, 0x4b2e1e}, {0x355d780, 0x4}, {0xc001591f08, 0x1, 0x7f30813dd060})\n\t/usr/local/golang/1.10.8/go/src/reflect/value.go:543 +0x814\nreflect.Value.Call({0x2d38480, 0xc0009b8070, 0x4517f2}, {0xc001591f08, 0x1, 0x1})\n\t/usr/local/golang/1.10.8/go/src/reflect/value.go:339 +0xc5\ngithub.com/traefik/yaegi/interp.callBin.func1({0x2d38480, 0xc0009b8070, 0x0}, {0xc001591f08, 0xc000754498, 0x4ae4dc})\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1472 +0x28\ngithub.com/traefik/yaegi/interp.callBin.func10(0xc0015ca4d0)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1646 +0x158\ngithub.com/traefik/yaegi/interp.runCfg(0xc0009ebb00, 0xc0015ca4d0, 0x39, 0x2d464c0)\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x2ac\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0xc0015d8840, 0x4, 0x8})\n\t/home/semaphore/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/run.go:1023 +0x4a5\nreflect.Value.call({0xc0015a4a00, 0xc000ae0bd0, 0x7f30a8447108}, {0x355d780, 0x4}, {0xc000755458, 0x4, 0xc00006c400})\n\t/usr/local/golang/1.10.8/go/src/reflect/value.go:543 +0x814\nreflect.Value.Call({0xc0015a4a00, 0xc000ae0bd0, 0xc000774ae0}, {0xc000755458, 0x4, 0x4})\n\t/usr/local/golang/1.10.8/go/src/reflect/value.go:339 +0xc5\ngithub.com/traefik/traefik/v2/pkg/plugins.(*Middleware).NewHandler(0xc000998ec0, {0x3b64980, 0xc000ae0630}, {0x7f30813e59b0, 0xc001591a88})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/plugins/middlewares.go:82 +0x2ee\ngithub.com/traefik/traefik/v2/pkg/server/middleware.(*Builder).buildConstructor.func23({0x7f30813e59b0, 0xc001591a88})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/middleware/middlewares.go:359 +0x3c\ngithub.com/traefik/traefik/v2/pkg/middlewares/tracing.Wrap.func1({0x7f30813e59b0, 0xc001591a88})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/tracing/wrapper.go:24 +0x5a\ngithub.com/traefik/traefik/v2/pkg/server/middleware.(*Builder).BuildChain.func1({0x7f30813e59b0, 0xc001591a88})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/middleware/middlewares.go:80 +0xf7\ngithub.com/containous/alice.Chain.Then({{0xc001591878, 0xc001591888, 0xc000adfad0}}, {0x3afdfa0, 0xc000fabee0})\n\t/home/semaphore/go/pkg/mod/github.com/containous/alice@v0.0.0-20181107144136-d83ebdd94cbd/chain.go:51 +0x90\ngithub.com/traefik/traefik/v2/pkg/server/router.(*Manager).buildHTTPHandler(0xc000755d40, {0x3b64980, 0xc000adfad0}, 0xc00159a1e0, {0xc00053c8e8, 0xc0007557e8})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/router/router.go:190 +0x5a5\ngithub.com/traefik/traefik/v2/pkg/server/router.(*Manager).buildRouterHandler(0xc000755d40, {0x3b64980, 0xc000adfad0}, {0xc00053c8e8, 0x12}, 0x7f3081471198)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/router/router.go:144 +0xac\ngithub.com/traefik/traefik/v2/pkg/server/router.(*Manager).buildEntryPointHandler(0x3b64910, {0x3b64980, 0xc000adf9b0}, 0x1)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/router/router.go:114 +0x1ea\ngithub.com/traefik/traefik/v2/pkg/server/router.(*Manager).BuildHandlers(0xc000755d40, {0x3b64910, 0xc00012c020}, {0xc0011a6480, 0x31d5620, 0x4}, 0x0)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/router/router.go:68 +0x27b\ngithub.com/traefik/traefik/v2/pkg/server.(*RouterFactory).CreateRouters(0xc0002d0f50, 0xc000a920c0)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/routerfactory.go:78 +0x26a\nmain.switchRouter.func1({0xc0011ebc50, 0xc00112f848, 0xc0011aee30, 0xc0011ebc80})\n\t/home/semaphore/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:374 +0x92\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).loadMessage(0xc00044a280, {{0x356887b, 0xc0002531a0}, 0xc001165ae0})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/configurationwatcher.go:156 +0x1b5\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).listenConfigurations(0xc00044a280, {0x3b648d8, 0xc0001276c0})\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/server/configurationwatcher.go:136 +0x45\ngithub.com/traefik/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:36 +0x66\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:59 +0x5b\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:53 +0x77\n"
```

**Comment by PascalMinder** [comment]
In the unit tests, it works.

Perhapts, could you change the line `unknownCountryCode = "nil"` to `unknowncountrycode: nil`

Have you configured all settings:
```
allowlocalrequests: false
loglocalrequests: false
logallowedrequests: false
logapirequests: false
api: "https://get.geojs.io/v1/ip/country/{ip}"
cachesize: 15
forcemonthlyupdate: false
allowunknowncountries: true
unknowncountrycode: nil
countries:
   - FR
```

**Comment by Thom-x** [comment]
Found it... 😅
README is wrong `unknowncountrycode: "nil"` it is `unknowncountryapiresponse`

**Comment by PascalMinder** [comment]
Ah shoot, I'll update the readme

**Comment by PascalMinder** [comment]
Ok, I corrected the read me. I also changed the yaml names of the configuration to camel case. I think it's easier to read. But I have to create a new release.
I also should change the release number format to the [SEM format](https://semver.org/) or so.
